junit2

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,29 +1,28 @@
 name: Building # Nombre del workflow
-on: # Ejecución condicional
-  push:
-#    tags:
-#      - "v*.*.*" # Filtra los pushes de forma que solo los que tenga una etiqueta con esta expresión 
-
-    jobs: # Solo haremos uno
-      building:
-        runs-on: ubuntu-latest
-        steps:
-          - uses: actions/checkout@v3 # Copiamos el repositorio
-          - uses: actions/setup-python@v4
-            with:
-              python-version: '3.10'
-          - name: Install Poetry
-            uses: snok/install-poetry@v1
-          - run: poetry build --junitxml=jest-junit.xml
-          - name: Publish to GH Releases
-            uses: dorny/test-reporter@v1
-            if: success() || failure()
-            with:
-              name: Test
-              path: reports/jest-*.xml
-              reporter: java-junit
-          - name: Publish to GH releases
-            if: startsWith(github.ref, 'refs/tags/v')
-            uses: softprops/action-gh-release@v1
-            with:
-              files: ${{ github.workspace }}/dist/*
+on: [push]
+jobs: # Solo vamos a crear uno
+  building:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3 # Copiamos el repositorio
+      - uses: actions/setup-python@v4
+        with:
+          python-version: '3.10'
+      - name: Install Poetry 
+        uses: snok/install-poetry@v1
+      - name: Install dependencies
+        run: poetry install
+      - name: Testing
+        run: poetry run pytest --junitxml=jest-junit.xml --cov=modeltools --cov-report=lcov --cov-report=xml
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Test            # Name of the check run which will be created
+          path: jest-junit.xml    # Path to test results
+          reporter: java-junit        # Format of test results
+      - name: Publish to GH Releases
+        if: startsWith(github.ref, 'refs/tags/v')
+        uses: softprops/action-gh-release@v1
+        with:
+          files: ${{ github.workspace }}/dist/*
